[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
serverAddress = "localhost"
serverPort = 8501

[logger]
level = "debug"

[runner]
magicEnabled = true

[global]
showWarningOnDirectExecution = true
